// Auto-generated by refresh.py — do not edit by hand.
window.DASHBOARD_DATA = {
  "last_updated": "28 Jul 2026, 09:22 PM IST",
  "window_start": "09 Jul",
  "window_end": "28 Jul 2026",
  "live": 425,
  "engagement": {
    "clicked": 387,
    "clicks": 9766,
    "ct_profiles": 685,
    "c1": 36,
    "c2": 29,
    "c3": 29,
    "c4plus": 293
  },
  "segments": {
    "clicked": {
      "base": 387,
      "active": 372,
      "slot": 348,
      "tech": 310,
      "install": 242,
      "tasks": 6558,
      "t_slot_prop": 3477,
      "t_slot_conf": 2664,
      "t_tech": 1953,
      "t_arrived": 978,
      "t_install": 925
    },
    "noclick": {
      "base": 38,
      "active": 37,
      "slot": 35,
      "tech": 26,
      "install": 9,
      "tasks": 795,
      "t_slot_prop": 243,
      "t_slot_conf": 205,
      "t_tech": 82,
      "t_arrived": 26,
      "t_install": 24
    },
    "nonmbg": {
      "base": 493,
      "active": 493,
      "slot": 344,
      "tech": 224,
      "install": 137,
      "tasks": 5950,
      "t_slot_prop": 2290,
      "t_slot_conf": 1925,
      "t_tech": 1123,
      "t_arrived": 463,
      "t_install": 387
    }
  },
  "enrolled_roster": {
    "total": 429,
    "with_leads": 392,
    "eff_60_plus": 91,
    "eff_60_minus": 301,
    "pending_only": 3,
    "no_activity": 34,
    "installs": 1268,
    "leads": 3011
  },
  "efficiency": {
    "june": {
      "enrolled": {
        "partners": 288,
        "leads": 854,
        "installs": 371,
        "agg_eff": 43.4,
        "secured": 95,
        "pct_secured": 33.0
      },
      "eligible": {
        "partners": 50,
        "leads": 96,
        "installs": 18,
        "agg_eff": 18.8,
        "secured": 4,
        "pct_secured": 8.0
      },
      "nonmbg": {
        "partners": 125,
        "leads": 362,
        "installs": 149,
        "agg_eff": 41.2,
        "secured": 38,
        "pct_secured": 30.4
      }
    },
    "july": {
      "enrolled": {
        "partners": 392,
        "leads": 3011,
        "installs": 1268,
        "agg_eff": 42.1,
        "secured": 91,
        "pct_secured": 23.2
      },
      "eligible": {
        "partners": 100,
        "leads": 513,
        "installs": 125,
        "agg_eff": 24.4,
        "secured": 9,
        "pct_secured": 9.0
      },
      "nonmbg": {
        "partners": 249,
        "leads": 1153,
        "installs": 342,
        "agg_eff": 29.7,
        "secured": 52,
        "pct_secured": 20.9
      }
    }
  }
};
