// Auto-generated by refresh.py — do not edit by hand.
window.DASHBOARD_DATA = {
  "last_updated": "18 Aug 2026, 12:31 PM IST",
  "window_start": "09 Jul",
  "window_end": "18 Aug 2026",
  "live": 425,
  "engagement": {
    "clicked": 415,
    "clicks": 24534,
    "ct_profiles": 972,
    "c1": 17,
    "c2": 19,
    "c3": 16,
    "c4plus": 363
  },
  "segments": {
    "clicked": {
      "base": 415,
      "active": 406,
      "slot": 405,
      "tech": 382,
      "install": 323,
      "tasks": 14039,
      "t_slot_prop": 10276,
      "t_slot_conf": 9386,
      "t_tech": 4856,
      "t_arrived": 2582,
      "t_install": 2468
    },
    "noclick": {
      "base": 10,
      "active": 10,
      "slot": 10,
      "tech": 9,
      "install": 3,
      "tasks": 376,
      "t_slot_prop": 212,
      "t_slot_conf": 202,
      "t_tech": 45,
      "t_arrived": 13,
      "t_install": 12
    },
    "nonmbg": {
      "base": 561,
      "active": 561,
      "slot": 518,
      "tech": 326,
      "install": 200,
      "tasks": 11392,
      "t_slot_prop": 7436,
      "t_slot_conf": 7045,
      "t_tech": 2861,
      "t_arrived": 1192,
      "t_install": 1066
    }
  },
  "enrolled_roster": {
    "total": 429,
    "with_leads": 419,
    "eff_60_plus": 77,
    "eff_60_minus": 342,
    "pending_only": 0,
    "no_activity": 10,
    "installs": 2819,
    "leads": 8171
  },
  "efficiency": {
    "june": {
      "enrolled": {
        "partners": 288,
        "leads": 854,
        "installs": 371,
        "agg_eff": 43.4,
        "secured": 95,
        "pct_secured": 33.0
      },
      "eligible": {
        "partners": 50,
        "leads": 96,
        "installs": 18,
        "agg_eff": 18.8,
        "secured": 4,
        "pct_secured": 8.0
      },
      "nonmbg": {
        "partners": 125,
        "leads": 362,
        "installs": 149,
        "agg_eff": 41.2,
        "secured": 38,
        "pct_secured": 30.4
      }
    },
    "july": {
      "enrolled": {
        "partners": 419,
        "leads": 8171,
        "installs": 2819,
        "agg_eff": 34.5,
        "secured": 77,
        "pct_secured": 18.4
      },
      "eligible": {
        "partners": 133,
        "leads": 1966,
        "installs": 355,
        "agg_eff": 18.1,
        "secured": 5,
        "pct_secured": 3.8
      },
      "nonmbg": {
        "partners": 381,
        "leads": 3361,
        "installs": 775,
        "agg_eff": 23.1,
        "secured": 50,
        "pct_secured": 13.1
      }
    }
  }
};
