// Auto-generated by refresh.py — do not edit by hand.
window.DASHBOARD_DATA = {
  "last_updated": "14 Jul 2026, 09:32 PM IST",
  "window_start": "09 Jul",
  "window_end": "14 Jul 2026",
  "live": 425,
  "engagement": {
    "clicked": 308,
    "clicks": 2159,
    "ct_profiles": 402,
    "c1": 72,
    "c2": 53,
    "c3": 43,
    "c4plus": 140
  },
  "segments": {
    "clicked": {
      "base": 308,
      "active": 278,
      "slot": 189,
      "tech": 174,
      "install": 114,
      "tasks": 1833,
      "t_slot_prop": 846,
      "t_slot_conf": 510,
      "t_tech": 434,
      "t_arrived": 217,
      "t_install": 198
    },
    "noclick": {
      "base": 117,
      "active": 105,
      "slot": 47,
      "tech": 36,
      "install": 12,
      "tasks": 761,
      "t_slot_prop": 171,
      "t_slot_conf": 96,
      "t_tech": 62,
      "t_arrived": 21,
      "t_install": 17
    },
    "nonmbg": {
      "base": 378,
      "active": 378,
      "slot": 141,
      "tech": 106,
      "install": 46,
      "tasks": 2152,
      "t_slot_prop": 534,
      "t_slot_conf": 320,
      "t_tech": 237,
      "t_arrived": 90,
      "t_install": 72
    }
  },
  "enrolled_roster": {
    "total": 429,
    "with_leads": 296,
    "eff_60_plus": 85,
    "eff_60_minus": 211,
    "pending_only": 33,
    "no_activity": 100,
    "installs": 516,
    "leads": 1121
  },
  "efficiency": {
    "june": {
      "enrolled": {
        "partners": 291,
        "leads": 874,
        "installs": 371,
        "agg_eff": 42.4,
        "secured": 92,
        "pct_secured": 31.6
      },
      "eligible": {
        "partners": 51,
        "leads": 100,
        "installs": 18,
        "agg_eff": 18.0,
        "secured": 4,
        "pct_secured": 7.8
      },
      "nonmbg": {
        "partners": 125,
        "leads": 368,
        "installs": 149,
        "agg_eff": 40.5,
        "secured": 37,
        "pct_secured": 29.6
      }
    },
    "july": {
      "enrolled": {
        "partners": 296,
        "leads": 1121,
        "installs": 516,
        "agg_eff": 46.0,
        "secured": 85,
        "pct_secured": 28.7
      },
      "eligible": {
        "partners": 53,
        "leads": 128,
        "installs": 38,
        "agg_eff": 29.7,
        "secured": 11,
        "pct_secured": 20.8
      },
      "nonmbg": {
        "partners": 143,
        "leads": 423,
        "installs": 133,
        "agg_eff": 31.4,
        "secured": 35,
        "pct_secured": 24.5
      }
    }
  }
};
