WITH base AS (
  SELECT CONNECTION_ID, CSP_ID,
    MAX_BY(CURRENT_STATE, UPDATED_AT) AS last_state,
    MAX_BY(REASON_CODE, UPDATED_AT) AS rc,
    MAX_BY(FAILURE_REASON, UPDATED_AT) AS fr,
    MAX_BY(FAILURE_SUBREASON_CODE, UPDATED_AT) AS fsc,
    MAX(CASE WHEN OTP_VERIFIED=TRUE OR INSTALLATION_COMPLETED_AT IS NOT NULL OR COMPLETED_STEP>=7 THEN 1 ELSE 0 END) AS has_installed,
    MAX(CASE WHEN CONFIRMED_SLOT_AT IS NOT NULL THEN 1 ELSE 0 END) AS reached_slot,
    TO_DATE(DATEADD(minute,330,MAX(UPDATED_AT))) AS last_date
  FROM PROD_DB.CSP_TAS_SERVICE_CSP_TAS_SERVICE.INSTALL_EXECUTION_CANDIDATES
  WHERE _FIVETRAN_ACTIVE=TRUE AND CSP_ID IS NOT NULL
    AND UPDATED_AT >= DATEADD(day,-120,CURRENT_DATE)
  GROUP BY CONNECTION_ID, CSP_ID
),
bucketed AS (
  SELECT *,
    CASE
      WHEN has_installed=1 THEN 'installed'
      WHEN last_state='DECLINED' THEN 'csp_denied'
      WHEN last_state='CANCELLED_BY_UPSTREAM' AND fr='TIMEOUT_P74' AND fsc='CSP_NO_SHOW' AND rc='ALLOCATION_ACCEPTED' THEN 'csp_no_show'
      WHEN fsc='CSP_NO_SHOW' THEN 'csp_abandoned'
      WHEN last_state='CANCELLED_BY_UPSTREAM' AND rc='TIMEOUT_P41' THEN 'csp_timeout'
      WHEN last_state='CANCELLED_BY_CUSTOMER' AND reached_slot=1 THEN 'cust_cancel_after_slot'
      WHEN last_state='CANCELLED_BY_CUSTOMER' AND reached_slot=0 THEN 'cust_cancel_before_slot'
      WHEN last_state='INSTALLATION_REPORTED_FAILED' THEN 'install_failed'
      WHEN last_state='CANCELLED_BY_UPSTREAM' THEN 'system_other'
      WHEN last_state='INSTALLATION_CANCELLED_ONSITE' THEN 'cancelled_onsite'
      ELSE 'open'
    END AS bucket
  FROM base
),
metrics AS (
  SELECT CSP_ID,
    COUNT_IF(bucket='installed' AND reached_slot=1 AND last_date>=DATE '2026-07-01') AS installs,
    COUNT_IF(reached_slot=1 AND bucket NOT IN ('open','system_other') AND last_date>=DATE '2026-07-01') AS denom,
    COUNT_IF(bucket='open') AS pending
  FROM bucketed
  GROUP BY CSP_ID
),
open_tk AS (
  SELECT CSP_ID, EXECUTION_CANDIDATE_ID, ZONE_ID, UPDATED_AT,
    CASE CURRENT_STATE
      WHEN 'ARRIVED_AT_SITE' THEN 8
      WHEN 'TECHNICIAN_ASSIGNED' THEN 7
      WHEN 'AWAITING_TECHNICIAN_ASSIGNMENT' THEN 6
      WHEN 'SLOT_CONFIRMED_BY_CUSTOMER' THEN 5
      WHEN 'SLOT_AUTO_CONFIRMED' THEN 5
      WHEN 'AWAITING_CUSTOMER_SLOT_CONFIRMATION' THEN 4
      WHEN 'SLOT_SELECTED' THEN 3
      WHEN 'AWAITING_SLOT_PROPOSAL' THEN 2
      ELSE 1 END AS rnk
  FROM PROD_DB.CSP_TAS_SERVICE_CSP_TAS_SERVICE.INSTALL_EXECUTION_CANDIDATES
  WHERE _FIVETRAN_ACTIVE=TRUE AND CSP_ID IS NOT NULL
    AND CURRENT_STATE IN ('ACCEPTED','AWAITING_SLOT_PROPOSAL','SLOT_SELECTED','AWAITING_CUSTOMER_SLOT_CONFIRMATION',
      'SLOT_CONFIRMED_BY_CUSTOMER','SLOT_AUTO_CONFIRMED','AWAITING_TECHNICIAN_ASSIGNMENT','TECHNICIAN_ASSIGNED',
      'ARRIVED_AT_SITE','INSTALLATION_IN_PROGRESS_PRE_FEE','FEE_COLLECTION_PENDING','INSTALLATION_IN_PROGRESS_POST_FEE','AWAITING_CUSTOMER_OTP')
),
tk_ranked AS (
  SELECT CSP_ID, EXECUTION_CANDIDATE_ID, ZONE_ID,
    ROW_NUMBER() OVER (PARTITION BY CSP_ID ORDER BY rnk DESC, UPDATED_AT ASC) AS rn
  FROM open_tk
),
tk AS (
  SELECT CSP_ID,
    MAX(CASE WHEN rn=1 THEN '#'||RIGHT(EXECUTION_CANDIDATE_ID,4) END) AS t1_no,
    MAX(CASE WHEN rn=1 THEN ZONE_ID END) AS t1_area,
    MAX(CASE WHEN rn=1 THEN EXECUTION_CANDIDATE_ID END) AS t1_cid,
    MAX(CASE WHEN rn=2 THEN '#'||RIGHT(EXECUTION_CANDIDATE_ID,4) END) AS t2_no,
    MAX(CASE WHEN rn=2 THEN ZONE_ID END) AS t2_area,
    MAX(CASE WHEN rn=2 THEN EXECUTION_CANDIDATE_ID END) AS t2_cid
  FROM tk_ranked WHERE rn<=2 GROUP BY CSP_ID
),
owner AS (   -- one representative userId per CSP (for mbg_id / tracking), owner preferred
  SELECT CSP_ID,
    MAX_BY(ID::string, CASE ROLE WHEN 'OWNER' THEN 3 WHEN 'MANAGER_PLUS' THEN 2 ELSE 1 END) AS user_id
  FROM PROD_DB.CSP_GATEWAY_SERVICE_CSP_GATEWAY_SERVICE.CSP_USER
  WHERE _FIVETRAN_ACTIVE=TRUE AND STATUS='ACTIVE'
    AND ROLE IN ('OWNER','MANAGER','MANAGER_PLUS') AND ID IS NOT NULL
  GROUP BY CSP_ID
)
SELECT m.CSP_ID AS csp_id, o.user_id,
  m.installs, m.denom, m.pending,
  tk.t1_no, tk.t1_area, tk.t1_cid, tk.t2_no, tk.t2_area, tk.t2_cid
FROM metrics m
LEFT JOIN tk    ON tk.CSP_ID = m.CSP_ID
LEFT JOIN owner o ON o.CSP_ID = m.CSP_ID
WHERE (m.installs + m.denom + m.pending) > 0
ORDER BY m.installs DESC, m.denom DESC
